дз
htmlacademy-javascript/1916729-kekstagram-simple-27 pull request #4
Opened 2022-10-04 14:54 UTC by maruh605

2022-10-05 04:49 UTC, Dima-Dim requested changes
Давай начнём с того, что ты посмотришь на ошибки которые находит линтер и попробуешь исправить их.

2022-10-06 09:15 UTC, Dima-Dim requested changes
Стало лучше, но ошибки линтер всё ещё находит.

2022-10-07 09:19 UTC, fallereugene commented
1. Рекомендую сразу внимательно ознакомиться с критериями оценки, чтобы меньше тратить времени на исправления.

2. Обрати внимание на нейминг: `randomInteger`, `checkStringLength`. Функции должны в твоем случае начинаться с глаголов (есть в критериях). Например, `getRandomInteger`, `isStringLengthValid`.

3. `checkStringLength` - не самое удачное наименование функции, так как по факту ты проверяешь валидна ли строка в разрезе длины и возвращаешь булев тип.

Именование должно быть таким, чтобы разработчик посмотрел на название и ему стало понятно назначение функции/переменной и т.д.

4. Не выполнено условие ТЗ:
```
Придумайте, как функция будет вести себя, если передать значение «до» меньшее, чем значение «от», или равное ему. Например, в этом случае функция также может возвращать NaN. Или же вы можете проверить, какой из аргументов больше, а какой меньше, и при необходимости поменять их местами. Возможны и другие варианты.

Функция может не гарантировать верный результат, если в переданном диапазоне нет ни одного подходящего числа.
```

2022-10-07 09:19 UTC, fallereugene commented on js/main.js
>  };
Должно быть единообразие.
Почему бы не использовать стрелочную функцию?

`const yourFunction = () => ...`

2022-10-07 09:20 UTC, merged